FROM public.ecr.aws/lambda/python:3.8

WORKDIR /app
COPY ./requirements.txt ./main ./ish /app/

RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY ./app /app/app
COPY ./slab /app/slab

ENV PYTHONPATH=/app:$PYTHONPATH

CMD ["app.web.api.handler"]