#!/usr/bin/env sh

if [[ $1 == 'web' ]]
then
  # E.g., ./main web --port 80
  uvicorn "app.web.api:app" --host "0.0.0.0" "${@:2}"
elif [[ $1 == 'ws' ]]
then
  PYTHONPATH=.:$PYTHONPATH python3 app/ws_main.py "${@:2}"
else
  PYTHONPATH=.:$PYTHONPATH python3 app/main.py "$@"
fi