#!/usr/bin/env sh

if [[ $1 == 'web' ]]
then
  # E.g., ./main web --port 80
  uvicorn "app.web.api:app" --host "0.0.0.0" "${@:2}"
elif [[ $1 == 'ish' ]]
then
  PYTHONPATH=.:$PYTHONPATH ipython "${@:2}"
else
  PYTHONPATH=.:$PYTHONPATH python3 app/main.py "${@:1}"
fi
