# Block index constants, used across everywhere. E.g, in DB table,
# As prefix for DynamoDB Partition keys etc.
BLOCKCHAIN_NONE = 0x000000
BLOCKCHAIN_ALL = 0xFF0000
BLOCKCHAIN_SOLANA = 0x010000
BLOCKCHAIN_TERRA = 0x020000
BLOCKCHAIN_ETHEREUM = 0x030000

SECONDARY_MARKET_FLAG = 0x00100

# NFT secondary market IDs
SOLANA_UNKNOWN = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x00  # 65792
SOLANA_MAGIC_EDEN = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x01  # 65793
SOLANA_ALPHA_ART = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x02  # 65794
SOLANA_DIGITAL_EYES = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x03  # 65795
SOLANA_SOLANART = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x04  # 65796
SOLANA_SOLSEA = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x05  # 65797
SOLANA_SMB = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x06  # 65798
SECONDARY_MARKET_EVENT_UNKNOWN = 0
SECONDARY_MARKET_EVENT_LISTING = 1
SECONDARY_MARKET_EVENT_DELISTING = 2
SECONDARY_MARKET_EVENT_SALE = 3
SECONDARY_MARKET_EVENT_PRICE_UPDATE = 4
EMPTY_PUBLIC_KEY = ''
EMPTY_TRANSACTION_HASH = ''