[FUNCTION]
NAME = "index-nft-data"

[LOCALSTACK]
ACTIVE = "true"
ENDPOINT = "http://localhost:4566"
REGION = "eu-central-1"

[KINESIS]
STREAM_NAME = "nft-data-stream"

[BLOCKCHAIN.ADDRESS]
SOLANA = "0x010000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
UPDATE = 4
BID = 5
SALE_AUCTION = 6
BIDDING = 7

[BLOCKCHAIN.ETHEREUM.HTTP]
ENDPOINT = "https://eth-mainnet.alchemyapi.io/v2"
TIMEOUT = 50
CONTRACT_METADATA_ENDPOINT = "https://eth-mainnet.g.alchemy.com/nft/v2"