[FUNCTION]
NAME = "index-nft-data"

[KINESIS]
STREAM_NAME = "nft-data-stream"

[BLOCKCHAIN.ADDRESS]
SOLANA = "0x010000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.SOLANA.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
UPDATE = 4
BID = 5
SALE_AUCTION = 6
BIDDING = 7