[APPLICATION]
NAME = "Data Insight API"

[OPENSEARCH]
HOST = "localhost.localstack.cloud"
PORT = 4566
TOKEN_FEED_INDEX = "token-feed-index"
DOMAIN = "my-demo"

[POSTGRES]
HOST = "localhost"
PORT = "5432"
MAX_CONNECTIONS = 10
DATABASE_NAME = "sintra-insight"

[BLOCKCHAIN.ADDRESS]
NONE = "0x000000"
ALL = "0xFF0000"
SOLANA = "0x010000"
TERRA = "0x020000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.MARKET]
FLAG = "0x00100"