import os

SOLANA_RPC_ENDPOINT = os.environ['SOLANA_RPC_ENDPOINT']
SOLANA_RPC_MAINNET_ENDPOINT = os.environ['SOLANA_RPC_MAINNET_ENDPOINT']
SOLANA_RPC_SERUM_ENDPOINT = os.environ['SOLANA_RPC_SERUM_ENDPOINT']
SOLANA_RPC_WSS_ENDPOINT = os.environ['SOLANA_RPC_WSS_ENDPOINT']
