import os
# For User table and indexes
DYNAMODB_USER_TABLE = os.environ['DYNAMODB_USER_TABLE']
DYNAMODB_USER_TABLE_GSI_EMAILS = os.environ['DYNAMODB_USER_TABLE_GSI_EMAILS']

# For NFT and collecions table
DYNAMODB_NFT_TABLE = os.environ['DYNAMODB_NFT_TABLE']
DYNAMODB_NFT_TABLE_GSI = os.environ['DYNAMODB_NFT_TABLE']

# For SME table and indexes, set through stacks repo
DYNAMODB_SME_TABLE = os.environ['DYNAMODB_SME_TABLE']
DYNAMODB_SME_TABLE_GSI_SME_ID = os.environ['DYNAMODB_SME_TABLE_GSI_SME_ID']
DYNAMODB_SME_TABLE_GSI_NFT_EVENTS = os.environ['DYNAMODB_SME_TABLE_GSI_NFT_EVENTS']
DYNAMODB_SME_TABLE_GSI_COLLECTION_EVENTS = os.environ['DYNAMODB_SME_TABLE_GSI_COLLECTION_EVENTS']
DYNAMODB_SME_TABLE_LSI_TIMESTAMP = os.environ['DYNAMODB_SME_TABLE_LSI_TIMESTAMP']
DYNAMODB_SME_TABLE_LSI_NFT_NAME = os.environ['DYNAMODB_SME_TABLE_LSI_NFT_NAME']
DYNAMODB_SME_TABLE_LSI_EVENTS = os.environ['DYNAMODB_SME_TABLE_LSI_EVENTS']
DYNAMODB_SME_TABLE_LSI_BUY_LISTING_EVENTS = os.environ['DYNAMODB_SME_TABLE_LSI_BUY_LISTING_EVENTS']
