from sintra.lambdas.shared.constants import BLOCKCHAIN_SOLANA

SECONDARY_MARKET_FLAG = 0x00100

SOLANA_UNKNOWN = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x00  # 65792
SOLANA_MAGIC_EDEN = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x01  # 65793
SOLANA_ALPHA_ART = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x02  # 65794
SOLANA_DIGITAL_EYES = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x03  # 65795
SOLANA_SOLANART = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x04  # 65796
SOLANA_SOLSEA = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x05  # 65797
SOLANA_SMB = BLOCKCHAIN_SOLANA | SECONDARY_MARKET_FLAG | 0x06  # 65798

SECONDARY_MARKET_EVENT_UNKNOWN = 0
SECONDARY_MARKET_EVENT_LISTING = 1
SECONDARY_MARKET_EVENT_DELISTING = 2
SECONDARY_MARKET_EVENT_SALE = 3
SECONDARY_MARKET_EVENT_PRICE_UPDATE = 4
SECONDARY_MARKET_EVENT_BID = 5
SECONDARY_MARKET_EVENT_SALE_AUCTION = 6
SECONDARY_MARKET_EVENT_CANCEL_BIDDING = 7


# Constants for transaction parsing

# Solana Internals
# https://docs.rs/solana-sdk/1.8.6/solana_sdk/system_instruction/enum.SystemInstruction.html
# u32 for function offset enum lookup
SYS_CREATE_ACCOUNT = 0
SYS_ASSIGN = 1
SYS_TRANSFER = 2
SYS_CREATE_ACCOUNT_WITH_SEED = 3
SYS_ADVANCE_NONCE_ACCOUNT = 4
SYS_WITHDRAW_NONCE_ACCOUNT = 5
SYS_INITIALIZE_NONCE_ACCOUNT = 6
SYS_AUTHORIZE_NONCE_ACCOUNT = 7
SYS_ALLOCATE = 8
SYS_ALLOCATE_WITH_SEED = 9
SYS_ASSIGN_WITH_SEED = 0xa
SYS_TRANSFER_WITH_SEED = 0xb

# https://github.com/solana-labs/solana-program-library/blob/c24bc966f133fbac5c789f7fb2841e47764ee0f2/token/program/inc/token.h#L104
# u8 for function offset enum lookup
TOKEN_INITIALIZE_MINT = 0
TOKEN_INITIALIZE_ACCOUNT = 1
TOKEN_INITIALIZE_MULTISIG = 2
TOKEN_TRANSFER = 3
TOKEN_APPROVE = 4
TOKEN_REVOKE = 5
TOKEN_SET_AUTHORITY = 6
TOKEN_MINTTO = 7
TOKEN_BURN = 8
TOKEN_CLOSE_ACCOUNT = 9
TOKEN_FREEZE_ACCOUNT = 0xa
TOKEN_THAW_ACCOUNT = 0xb
TOKEN_TRANSFER_CHECKED = 0xc
TOKEN_APPROVE_CHECKED = 0xd
TOKEN_MINTTO_CHECKED = 0xe
TOKEN_BURN_CHECKED = 0xf

# For TOKEN_SET_AUTHORITY type
# https://github.com/solana-labs/solana-program-library/blob/1c417ffa4f9874a8df43a39746a790224421b13b/token/program-2022/inc/token.h#L50
TOKEN_AUTHORITY_TYPE_MINT_TOKENS = 0
TOKEN_AUTHORITY_TYPE_FREEZE_ACCOUNT = 1
TOKEN_AUTHORITY_TYPE_ACCOUNT_OWNER = 2
TOKEN_AUTHORITY_TYPE_CLOSE_ACCOUNT = 3
