[FUNCTION]
NAME = "signature-instruction"

[KINESIS]
STREAM_NAME = "secondary-market"

[LOCALSTACK]
ACTIVE = "true"
ENDPOINT = "http://localhost:4566"
REGION = "eu-central-1"

[BLOCKCHAIN.MARKET]
FLAG = "0x00100"

[BLOCKCHAIN.ADDRESS]
NONE = "0x000000"
ALL = "0xFF0000"
SOLANA = "0x010000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
PRICE_UPDATE = 4
BID = 5
SALE_AUCTION = 6
CANCEL_BIDDING = 7

[BLOCKCHAIN.SOLANA.HTTP]
ENDPOINT = "https://ssc-dao.genesysgo.net"
TIMEOUT = 50

[BLOCKCHAIN.SOLANA.METAPLEX]
SYSTEM_PROGRAM_ID = '11111111111111111111111111111111'
TOKEN_PROGRAM_ID = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
METADATA_PROGRAM = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'

[BLOCKCHAIN.SOLANA.MARKET.MAGIC_EDEN]
ADDRESS = "GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp"
PROGRAM_ACCOUNT_V1 = "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"
PROGRAM_ACCOUNT_V2 = "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"
AUCTION_PROGRAM_ACCOUNT = "EA15T2W45BJFm71XmB5VGcsiWGKZTNfnK6aCmE2Hb5eC"

[BLOCKCHAIN.SOLANA.MARKET.ALPHA_ART]
ADDRESS = "4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw"
PROGRAM_ACCOUNT = "HZaWndaNWHFDd9Dhk5pqUUtsmoBCqzb1MLu3NAh1VX6B"

[BLOCKCHAIN.SOLANA.MARKET.SOLSEA]
ADDRESS = ""
PROGRAM_ACCOUNT = "617jbWo616ggkDxvW1Le8pV38XLbVSyWY8ae6QUmGBAU"

[BLOCKCHAIN.SOLANA.MARKET.SOLANART]
ADDRESS = "3D49QorJyNaL4rcpiynbuS3pRH4Y7EXEM6v6ZGaqfFGK"
PROGRAM_ACCOUNT = "CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz"

[BLOCKCHAIN.SOLANA.MARKET.EXCHANGE_ART]
PROGRAM_ACCOUNT_V1 = 'AmK5g2XcyptVLCFESBCJqoSfwV3znGoVYQnqEnaAZKWn'
PROGRAM_ACCOUNT_V2 = 'exofLDXJoFji4Qyf9jSAH59J4pp82UT5pmGgR6iT24Z'
AUCTION_PROGRAM_ACCOUNT = 'exAuvFHqXXbiLrM4ce9m1icwuSyXytRnfBkajukDFuB'

[BLOCKCHAIN.SOLANA.MARKET.DIGITAL_EYES]
ADDRESS = "DMao6jeMKktKu58WtjS9aPZLiRzwFUGeUvSahvrTx5AQ"
PROGRAM_ACCOUNT_V1 = "A7p8451ktDCHq5yYaHczeLMYsjRsAkzc3hCXcSrwYHU7"
PROGRAM_ACCOUNT_V2 = "7t8zVJtPCFAqog1DcnB6Ku1AVKtWfHkCiPi1cAvcJyVF"

[BLOCKCHAIN.SOLANA.MARKET.MONKEY_BUSINESS]
PROGRAM_ACCOUNT_V1 = 'GvQVaDNLV7zAPNx35FqWmgwuxa4B2h5tuuL73heqSf1C'
PROGRAM_ACCOUNT_V2 = 'J7RagMKwSD5zJSbRQZU56ypHUtux8LRDkUpAPSKH4WPp'
PROGRAM_ACCOUNT_V3 = '5ZfZAwP2m93waazg8DkrrVmsupeiPEvaEHowiUP7UAbJ'

[BLOCKCHAIN.SOLANA.MARKET.OPEN_SEA]
PROGRAM_ACCOUNT = 'M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'
AUCTION_PROGRAM_ACCOUNT = 'hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk'

[BLOCKCHAIN.ETHEREUM.MARKET.OPEN_SEA]
PROGRAM_ACCOUNT_V1 = "0x7Be8076f4EA4A4AD08075C2508e481d6C946D12b"
PROGRAM_ACCOUNT_V2 = "0x7f268357A8c2552623316e2562D90e642bB538E5"

[BLOCKCHAIN.SOLANA.INTERNAL.SYSTEM]
CREATE_ACCOUNT = 0
ASSIGN = 1
TRANSFER = 2
CREATE_ACCOUNT_WITH_SEED = 3
ADVANCE_NONCE_ACCOUNT = 4
WITHDRAW_NONCE_ACCOUNT = 5
INITIALIZE_NONCE_ACCOUNT = 6
AUTHORIZE_NONCE_ACCOUNT = 7
ALLOCATE = 8
ALLOCATE_WITH_SEED = 9
ASSIGN_WITH_SEED = 10
TRANSFER_WITH_SEED = 11

[BLOCKCHAIN.SOLANA.INTERNAL.TOKEN]
INITIALIZE_MINT = 0
INITIALIZE_ACCOUNT = 1
INITIALIZE_MULTISIG = 2
TRANSFER = 3
APPROVE = 4
REVOKE = 5
SET_AUTHORITY = 6
MINTTO = 7
BURN = 8
CLOSE_ACCOUNT = 9
FREEZE_ACCOUNT = 10
THAW_ACCOUNT = 11
TRANSFER_CHECKED = 12
APPROVE_CHECKED = 13
MINTTO_CHECKED = 14
BURN_CHECKED = 15

[BLOCKCHAIN.SOLANA.INTERNAL.AUTHORITY]
MINT_TOKENS = 0
FREEZE_ACCOUNT = 1
ACCOUNT_OWNER = 2
CLOSE_ACCOUNT = 3