[FUNCTION]
NAME = "signature-instruction"

[KINESIS]
STREAM_NAME = "secondary-market"

[BLOCKCHAIN.MARKET]
FLAG = "0x00100"

[BLOCKCHAIN.ADDRESS]
NONE = "0x000000"
ALL = "0xFF0000"
SOLANA = "0x010000"

[BLOCKCHAIN.SOLANA.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
UPDATE = 4
BID = 5
SALE_AUCTION = 6
BIDDING = 7

[BLOCKCHAIN.SOLANA.HTTP]
ENDPOINT = "https://api.devnet.solana.com"
TIMEOUT = 50

[BLOCKCHAIN.SOLANA.METAPLEX]
SYSTEM_PROGRAM_ID = '11111111111111111111111111111111'
TOKEN_PROGRAM_ID = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
METADATA_PROGRAM = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'

[BLOCKCHAIN.SOLANA.MARKET.MAGIC_EDEN]
ADDRESS = "GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp"
PROGRAM_ACCOUNT_V1 = "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"
PROGRAM_ACCOUNT_V2 = "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"
AUCTION_PROGRAM_ACCOUNT = "EA15T2W45BJFm71XmB5VGcsiWGKZTNfnK6aCmE2Hb5eC"

[BLOCKCHAIN.SOLANA.MARKET.ALPHA_ART]
ADDRESS = "4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw"
PROGRAM_ACCOUNT = "HZaWndaNWHFDd9Dhk5pqUUtsmoBCqzb1MLu3NAh1VX6B"

[BLOCKCHAIN.SOLANA.INTERNAL.SYSTEM]
CREATE_ACCOUNT = 0
ASSIGN = 1
TRANSFER = 2
CREATE_ACCOUNT_WITH_SEED = 3
ADVANCE_NONCE_ACCOUNT = 4
WITHDRAW_NONCE_ACCOUNT = 5
INITIALIZE_NONCE_ACCOUNT = 6
AUTHORIZE_NONCE_ACCOUNT = 7
ALLOCATE = 8
ALLOCATE_WITH_SEED = 9
ASSIGN_WITH_SEED = 10
TRANSFER_WITH_SEED = 11

[BLOCKCHAIN.SOLANA.INTERNAL.TOKEN]
INITIALIZE_MINT = 0
INITIALIZE_ACCOUNT = 1
INITIALIZE_MULTISIG = 2
TRANSFER = 3
APPROVE = 4
REVOKE = 5
SET_AUTHORITY = 6
MINTTO = 7
BURN = 8
CLOSE_ACCOUNT = 9
FREEZE_ACCOUNT = 10
THAW_ACCOUNT = 11
TRANSFER_CHECKED = 12
APPROVE_CHECKED = 13
MINTTO_CHECKED = 14
BURN_CHECKED = 15

[BLOCKCHAIN.SOLANA.INTERNAL.AUTHORITY]
MINT_TOKENS = 0
FREEZE_ACCOUNT = 1
ACCOUNT_OWNER = 2
CLOSE_ACCOUNT = 3