[FUNCTION]
NAME = "fetch-nft-metadata"

[LOCALSTACK]
ACTIVE = "true"
ENDPOINT = "http://localhost:4566"
REGION = "eu-central-1"

[BLOCKCHAIN.ADDRESS]
NONE = "0x000000"
ALL = "0xFF0000"
SOLANA = "0x010000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
UPDATE = 4
BID = 5
SALE_AUCTION = 6
BIDDING = 7

[KINESIS]
STREAM_NAME = "nft-metadata-stream"

[BLOCKCHAIN.SOLANA.HTTP]
ENDPOINT = "https://api.devnet.solana.com"
TIMEOUT = 50

[BLOCKCHAIN.ETHEREUM.HTTP]
ENDPOINT = "https://eth-mainnet.alchemyapi.io/v2"
TIMEOUT = 50