METAPLEX_PUBKEY = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
MAGIC_EDEN = "Magic Eden"
ALPHA_ART = "Alpha Art"
MAGIC_EDEN_ADDRESS = "GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp"
ALPHA_ART_ADDRESS = "4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw"
### Enable this later
# DIGITAL_EYES_ADDRESS = "F4ghBzHFNgJxV4wEQDchU5i7n4XWWMBSaq7CuswGiVsr"

NUM_CREATORS = 2
