from app.blockchains.shared import (
    SOLANA_MAGIC_EDEN,
    SOLANA_ALPHA_ART,
    SOLANA_DIGITAL_EYES,
    SOLANA_SOLANART,
    SOLANA_SOLSEA,
    SOLANA_SMB,
    EMPTY_PUBLIC_KEY
)

from spl.token.constants import *  # noqa

SYSTEM_PROGRAM_ID = '11111111111111111111111111111111'
TOKEN_PROGRAM_ID = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
METAPLEX_METADATA_PROGRAM = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'

MAGIC_EDEN_ADDRESS = "GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp"
MAGIC_EDEN_PROGRAM_ACCOUNT = "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"

ALPHA_ART_ADDRESS = "4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw"
ALPHA_ART_PROGRAM_ACCOUNT = "HZaWndaNWHFDd9Dhk5pqUUtsmoBCqzb1MLu3NAh1VX6B"

DIGITAL_EYES_ADDRESS = "DMao6jeMKktKu58WtjS9aPZLiRzwFUGeUvSahvrTx5AQ"
DIGITAL_EYES_PROGRAM_ACCOUNT = "7t8zVJtPCFAqog1DcnB6Ku1AVKtWfHkCiPi1cAvcJyVF"
DIGITAL_EYES_SALE_PROGRAM_ACCOUNT = "A7p8451ktDCHq5yYaHczeLMYsjRsAkzc3hCXcSrwYHU7"

SOLANART_ADDRESS = "3D49QorJyNaL4rcpiynbuS3pRH4Y7EXEM6v6ZGaqfFGK"
SOLANART_PROGRAM_ACCOUNT = "CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz"

SOLSEA_ADDRESS = EMPTY_PUBLIC_KEY  # Not used in our case.
SOLSEA_PROGRAM_ACCOUNT = "617jbWo616ggkDxvW1Le8pV38XLbVSyWY8ae6QUmGBAU"

# Specific Markets
SOLANA_MONKEY_BUSINESS_PROGRAM_ACCOUNT = 'GvQVaDNLV7zAPNx35FqWmgwuxa4B2h5tuuL73heqSf1C'

MARKET_NAME_MAP = {
    SOLANA_MAGIC_EDEN: "Magic Eden",
    SOLANA_ALPHA_ART: "Alpha Art",
    SOLANA_SOLANART: "Solanart",
    SOLANA_DIGITAL_EYES: "Digital Eyes",
    SOLANA_SOLSEA: "Solsea",
    SOLANA_SMB: 'Solana Monkey Business',
}

MARKET_ADDRESS_MAP = {
    SOLANA_MAGIC_EDEN: MAGIC_EDEN_ADDRESS,
    SOLANA_ALPHA_ART: ALPHA_ART_ADDRESS,
    SOLANA_SOLANART: SOLANART_ADDRESS,
    SOLANA_DIGITAL_EYES: DIGITAL_EYES_ADDRESS,
    SOLANA_SOLSEA: SOLSEA_ADDRESS,
    # TODO: Maybe change this to the address
    SOLANA_SMB: SOLANA_MONKEY_BUSINESS_PROGRAM_ACCOUNT,
}

MARKET_PROGRAM_ID_MAP = {
    MAGIC_EDEN_PROGRAM_ACCOUNT: SOLANA_MAGIC_EDEN,
    ALPHA_ART_PROGRAM_ACCOUNT: SOLANA_ALPHA_ART,
    DIGITAL_EYES_PROGRAM_ACCOUNT: SOLANA_DIGITAL_EYES,
    DIGITAL_EYES_SALE_PROGRAM_ACCOUNT: SOLANA_DIGITAL_EYES,
    SOLANART_PROGRAM_ACCOUNT: SOLANA_SOLANART,
    SOLSEA_PROGRAM_ACCOUNT: SOLANA_SOLSEA,
    SOLANA_MONKEY_BUSINESS_PROGRAM_ACCOUNT: SOLANA_SMB,
}

# Constants for transaction parsing


# Solana Internals
# https://docs.rs/solana-sdk/1.8.6/solana_sdk/system_instruction/enum.SystemInstruction.html
# u32 for function offset enum lookup
SYS_CREATE_ACCOUNT = 0
SYS_ASSIGN = 1
SYS_TRANSFER = 2
SYS_CREATE_ACCOUNT_WITH_SEED = 3
SYS_ADVANCE_NONCE_ACCOUNT = 4
SYS_WITHDRAW_NONCE_ACCOUNT = 5
SYS_INITIALIZE_NONCE_ACCOUNT = 6
SYS_AUTHORIZE_NONCE_ACCOUNT = 7
SYS_ALLOCATE = 8
SYS_ALLOCATE_WITH_SEED = 9
SYS_ASSIGN_WITH_SEED = 0xa
SYS_TRANSFER_WITH_SEED = 0xb

# https://github.com/solana-labs/solana-program-library/blob/c24bc966f133fbac5c789f7fb2841e47764ee0f2/token/program/inc/token.h#L104
# u8 for function offset enum lookup
TOKEN_INITIALIZE_MINT = 0
TOKEN_INITIALIZE_ACCOUNT = 1
TOKEN_INITIALIZE_MULTISIG = 2
TOKEN_TRANSFER = 3
TOKEN_APPROVE = 4
TOKEN_REVOKE = 5
TOKEN_SET_AUTHORITY = 6
TOKEN_MINTTO = 7
TOKEN_BURN = 8
TOKEN_CLOSE_ACCOUNT = 9
TOKEN_FREEZE_ACCOUNT = 0xa
TOKEN_THAW_ACCOUNT = 0xb
TOKEN_TRANSFER_CHECKED = 0xc
TOKEN_APPROVE_CHECKED = 0xd
TOKEN_MINTTO_CHECKED = 0xe
TOKEN_BURN_CHECKED = 0xf

# For TOKEN_SET_AUTHORITY type
# https://github.com/solana-labs/solana-program-library/blob/1c417ffa4f9874a8df43a39746a790224421b13b/token/program-2022/inc/token.h#L50
TOKEN_AUTHORITY_TYPE_MINT_TOKENS = 0
TOKEN_AUTHORITY_TYPE_FREEZE_ACCOUNT = 1
TOKEN_AUTHORITY_TYPE_ACCOUNT_OWNER = 2
TOKEN_AUTHORITY_TYPE_CLOSE_ACCOUNT = 3
