# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy the changes to the AWS Lambda function we specified.

name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2
  ECR_REPO_URI: 391319738221.dkr.ecr.us-west-2.amazonaws.com/nft-service
  FUNCTION_NAME: arn:aws:lambda:us-west-2:822618759175:function:NftAPIServiceStack-NftServiceApiFuncD04E88BA-WrCoOKt9PMsK
  COGNITO_APP_CLIENT_ID: 1e3u6mprmqsvnf131dns9aa4oo
  DEPLOYMENT_ENV: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_REPO_URI

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG2: ${{ env.DEPLOYMENT_ENV }}-latest  # Used for initial API gateway code update.
        run: |
          docker build -f ./Dockerfile-lambda -t $ECR_REPO_URI:$IMAGE_TAG -t $ECR_REPO_URI:$IMAGE_TAG2 .
          docker push --all-tags $ECR_REPO_URI
          echo "::set-output name=image::$ECR_REPO_URI:$IMAGE_TAG"

      - name: Update Lambda Function code
        id: update-function-code
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
        run: |
          aws lambda update-function-configuration --function-name ${{ env.FUNCTION_NAME }} \
            --environment '{
              "Variables": {
                "COGNITO_PUBLIC_KEYS": "ssm:///${{ env.DEPLOYMENT_ENV }}/sintra-nft-service/v1/cognito_public_keys",
                "COGNITO_APP_CLIENT_ID": "${{ COGNITO_APP_CLIENT_ID }}"
            }'
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri $IMAGE_URI