# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy the changes to the AWS Lambda function we specified.

name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2
  ECR_REPO_URI: 391319738221.dkr.ecr.us-west-2.amazonaws.com/nft-service
  DEPLOYMENT_ENV: dev
#  FUNCTION_NAME: arn:aws:lambda:us-west-2:822618759175:function:NftAPIServiceStack-NftServiceApiFuncD04E88BA-WrCoOKt9PMsK
#  COGNITO_APP_CLIENT_ID: 1e3u6mprmqsvnf131dns9aa4oo


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_REPO_URI

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_TAG2: ${{ env.DEPLOYMENT_ENV }}-latest  # Used for initial API gateway code update.
        run: |
          IMAGE_TAG="$(echo ${GITHUB_SHA} | cut -c1-7)"
          docker build -f Dockerfile -t $ECR_REPO_URI:$IMAGE_TAG -t $ECR_REPO_URI:$IMAGE_TAG2 .
          docker push --all-tags $ECR_REPO_URI
          echo "::set-output name=image::$ECR_REPO_URI:$IMAGE_TAG"
          echo "::set-output name=github_sha::$IMAGE_TAG"

      # Do not do deploy here. Use `sintra-stacks` to push deployment.
      - name: Update Lambda Function env vars
        id: update-function-code
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
          GITHUB_SHA: ${{ steps.build-image.outputs.github_sha }}
        run: |
          aws lambda update-function-configuration --function-name ${{ env.FUNCTION_NAME }} \
            --environment '{
              "Variables": {
                "GITHUB_SHA": ${GITHUB_SHA}
            }'