[WORKER]
TYPE = "ethereum"
NAME = "ethereum_worker"

[BLOCKCHAIN.ADDRESS]
NONE = "0x000000"
ALL = "0xFF0000"
SOLANA = "0x010000"
TERRA = "0x020000"
ETHEREUM = "0x030000"

[BLOCKCHAIN.SOLANA.HTTP]
ENDPOINT = "https://ssc-dao.genesysgo.net"
TIMEOUT = 50

[BLOCKCHAIN.SOLANA.WS]
ENDPOINT = "wss://ssc-dao.genesysgo.net"
TIMEOUT = 50

[BLOCKCHAIN.ETHEREUM.HTTP]
ENDPOINT = "https://eth-mainnet.alchemyapi.io/v2"
TIMEOUT = 50

[BLOCKCHAIN.ETHEREUM.WS]
ENDPOINT = "wss://eth-mainnet.alchemyapi.io/v2"
TIMEOUT = 50

[BLOCKCHAIN.MARKET]
FLAG = "0x00100"

[BLOCKCHAIN.MARKET.EVENT]
UNKNOWN = 0
LISTING = 1
DELISTING = 2
SALE = 3
UPDATE = 4
BID = 5
SALE_AUCTION = 6
BIDDING = 7

[BLOCKCHAIN.SOLANA.MARKET.MAGIC_EDEN]
ADDRESS = "GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp"
PROGRAM_ACCOUNT = "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"
PROGRAM_ACCOUNT_V2 = "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"
AUCTION_PROGRAM_ACCOUNT = "EA15T2W45BJFm71XmB5VGcsiWGKZTNfnK6aCmE2Hb5eC"

[BLOCKCHAIN.SOLANA.MARKET.ALPHA_ART]
ADDRESS = "4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw"
PROGRAM_ACCOUNT = "HZaWndaNWHFDd9Dhk5pqUUtsmoBCqzb1MLu3NAh1VX6B"

[BLOCKCHAIN.SOLANA.MARKET.DIGITAL_EYES]
ADDRESS = "DMao6jeMKktKu58WtjS9aPZLiRzwFUGeUvSahvrTx5AQ"
NFT_MARKETPLACE_PROGRAM_ACCOUNT = "A7p8451ktDCHq5yYaHczeLMYsjRsAkzc3hCXcSrwYHU7"
DIRECT_SELL_PROGRAM_ACCOUNT = "7t8zVJtPCFAqog1DcnB6Ku1AVKtWfHkCiPi1cAvcJyVF"

[BLOCKCHAIN.SOLANA.MARKET.SOLANART]
ADDRESS = "3D49QorJyNaL4rcpiynbuS3pRH4Y7EXEM6v6ZGaqfFGK"
PROGRAM_ACCOUNT = "CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz"

[BLOCKCHAIN.SOLANA.MARKET.SOLSEA]
ADDRESS = ""
PROGRAM_ACCOUNT = "617jbWo616ggkDxvW1Le8pV38XLbVSyWY8ae6QUmGBAU"

[BLOCKCHAIN.SOLANA.MARKET.MONKEY_BUSINESS]
PROGRAM_ACCOUNT = 'GvQVaDNLV7zAPNx35FqWmgwuxa4B2h5tuuL73heqSf1C'
PROGRAM_ACCOUNT_V2 = 'J7RagMKwSD5zJSbRQZU56ypHUtux8LRDkUpAPSKH4WPp'
PROGRAM_ACCOUNT_V3 = '5ZfZAwP2m93waazg8DkrrVmsupeiPEvaEHowiUP7UAbJ'

[BLOCKCHAIN.SOLANA.MARKET.OPEN_SEA]
PROGRAM_ACCOUNT = 'M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'
AUCTION_PROGRAM_ACCOUNT = 'hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk'

[BLOCKCHAIN.SOLANA.MARKET.EXCHANGE_ART]
PROGRAM_ACCOUNT = 'AmK5g2XcyptVLCFESBCJqoSfwV3znGoVYQnqEnaAZKWn'
PROGRAM_ACCOUNT_V2 = 'exofLDXJoFji4Qyf9jSAH59J4pp82UT5pmGgR6iT24Z'
AUCTION_PROGRAM_ACCOUNT = 'exAuvFHqXXbiLrM4ce9m1icwuSyXytRnfBkajukDFuB'

[BLOCKCHAIN.ETHEREUM.MARKET.OPEN_SEA]
PROGRAM_ACCOUNT = "0x7Be8076f4EA4A4AD08075C2508e481d6C946D12b"
PROGRAM_ACCOUNT_V2 = "0x7f268357A8c2552623316e2562D90e642bB538E5"

[KINESIS]
STREAM = "transaction-signatures"
REGION = "eu-central-1"

[SECRETSMANAGER]
REGION = "eu-central-1"

[LOCALSTACK]
ACTIVE = "true"
ENDPOINT = "http://localhost:4566"
REGION = "eu-central-1"
